package com.jwtsecurity.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.jwtsecurity.model.User;
import com.jwtsecurity.model.UserRequest;
import com.jwtsecurity.model.UserResponse;
import com.jwtsecurity.service.UserImpl;
import com.jwtsecurity.util.JwtUtil;

//http://localhost:8080/user/save  -----> Add User

@RestController
@RequestMapping("/user")
public class UserController {
	@Autowired
	private UserImpl service;
	
	@Autowired(required = true)
	private JwtUtil util;

	// 1.save user data in database.

	@PostMapping("/save")
	public ResponseEntity<String> saveUser(@RequestBody User user) {

		Integer id = service.saveUser(user);

		String body = "User" + id + "saved!!!";

		// return new ResponseEntity<String>(body,HttpStatus.OK);

		return ResponseEntity.ok(body);

	}
	
	
	
	//2. valid user and generated Token.
	
	@PostMapping("/login")
	public ResponseEntity<UserResponse> loginuser(@RequestBody UserRequest request){
		
		
		//TODO: Valid username & password with DB.
		
		String token =util.generateToken(request.getUsername());
		
		return ResponseEntity.ok(new UserResponse(token,"Success! generated by krishna"));
		
		
	}

}
